{
    "name": "Reporting Module",
    "version": "1.0",
    "depends": [
        "ad_sales_contract",
        #"ad_product_extended",
        "ad_letter_of_credit",
        "ad_partner_info_bitratex",
        "ad_product_info_bitratex",
        "ad_container_booking",
        "stock",
        "sale",
        "base",
        "account",
        "ad_stock_report",
        "ad_invoice_charge",
        ],
    "author": "Jhony - Bitratex",
    "category": "Warehouse",
    "description": """
     
    """,
    "init_xml": [],
    'update_xml': [
                    "inventory_issue/header_webkit.xml",
                    "inventory_issue/inventory_issue_view.xml",
                    "inventory_issue/production_receipt_view.xml",
                    "sales_confirmation/sales_confirmation_form_view.xml",
                    "commercial_invoice/account_print_invoice_form_view.xml",
                    "proforma_invoice/print_proforma_invoice_form_view.xml",
                    "lc_verification/lc_verification_cheklist_form.xml",
                    "packing_list/packinglist_print_form_view.xml",
                    "insurance_certificate_report/insurance_report.xml",
                    "incoming_shipment_report/incoming_shipment_form.xml",
                    "quality_certificate_report/quality_certificate_report.xml",
                    "delay_shipment/delay_shipment.xml",
                    "purchase_receipt_register/purchase_receipt_register_wizard_view.xml",
                    "issue_report/issue_report_wizard_view.xml",
                    "bpa_ext_trans/bill_passing_advise_of_other_emkl_cost.xml",
                    "detail_freight_cost/detail_freight_cost_view.xml",
                    "land_in_transit/land_in_transit_report.xml",
                    "land_in_transit/land_in_transit_exp_report.xml",
                    "new_product_request/new_product_request_report.xml",
                    "sca_report/sca_report.xml",
                    "department_return/department_return_view.xml",
                    "purchase_receipt_register/purchase_receipt_register_daily_wizard_view.xml",
                    "stock_inventory/stock_inventory.xml",
                    "transfer_note/transfer_note.xml",
                    "stores_consumption/stores_consumption_wizard_view.xml",
                    "purchase_register/purchase_register_wizard_view.xml",
                    "purchase_register/purchase_register_daily_wizard_view.xml",
                    "waste/waste_transfer_summary_wizard.xml",
                    "item_history/item_history_wizard_view.xml",
                    "po_price_analysis/po_price_view.xml",
                    "otif_report/report_otif_wizard_view.xml",
                    "sale_order_priorities/sale_order_priority_view.xml",
                     "sale_order_priorities/sale_order_priority_xls.xml"
                   ],
    'demo_xml': [],
    'installable': True,
    'application':True,
    'auto_install': False,
}
