from . import res_partner
from . import account_invoice
from . import sale
from . import manufacture
from . import res_company
#from . import sale_order_delivery
from . import aliases
from . import advance_payment
from . import wizard
from . import stock
from . import container_booking
from . import res_country
from . import proforma_invoice
from . import letter_of_credit