{
    "name": "Sales Contract",
    "version": "7.0",
    "depends": ["base", "ad_ir_sequence_custom",
        "sale",
        "sale_set_to_draft",
        "product",
        "ad_port",
        "account",
        "stock",
        "sale_stock",
        "mrp",
        "ad_letter_of_credit",
        "ad_advance_payment",
        "ad_container_booking",
        "ad_product_info_bitratex"],
    "author": "Dedi - Adsoft",
    "category": "Sales",
    "description": """
     This modules is aimed to provide information and also sales business workflow in Bitratex Industries
    """,
    "init_xml": [],
    'update_xml': [
        "security/security.xml",
        "workflow/sale_wkf.xml",
        'res_partner_view.xml',
        'res_company_view.xml',
        "wizard/manual_delivery_wizard_view.xml",
        "wizard/sale_line_state_view.xml",
        "wizard/set_internal_remark_view.xml",
        "wizard/sale_order_from_stock_picking_view.xml",
        "wizard/wizard_input_export_freight_view.xml",
        'sale_view.xml',
        #'sale_order_delivery_view.xml',
        'advance_payment_view.xml',
        'manufacture_view.xml',
        'stock_view.xml',
        'container_booking_view.xml',
        'res_country_view.xml',
        'proforma_invoice_view.xml',
        'account_invoice_view.xml',
        'letter_of_credit_view.xml',
        "aliases_view.xml",
                   ],
    'demo_xml': [],
    'installable': True,
    'active': False,
    'application':True,
}