{
    "name": "Stock Report",
    "version": "7.0",
    "depends": ["base",
        "product",
        "stock",
        "sale_stock",
        "mrp",
        "ad_container_booking",
        "ad_product_info_bitratex",
        "ad_account_optimization",
        "ad_beacukai_report",
        ],
    "author": "Dedi - Adsoft",
    "category": "Warehouse",
    "description": """
     This modules is aimed to provide stock report in Bitratex Industries
    """,
    "init_xml": [],
    'update_xml': [
        "data/data.xml",
        #"stock_report.xml",
        "stock_move_view.xml",
        "valuation_view.xml",
        "wizard_stock_report.xml",
        "fg_stock_ageing_wizard_view.xml",
        "report_shipment_statement_wizard_view.xml",
        "summary_export_shipment_report_wizard_view.xml",
        "summary_stock_wizard_view.xml",
        "ipp_wizard_view.xml",
        "summary_stock_ageing_wizard_view.xml",
                   ],
    'demo_xml': [],
    'installable': True,
    'active': False,
    'application':True,
}