{
    "name": "Purchases Report",
    "version": "7.0",
    "depends": ["base",
        "ad_purchase_order_bitratex",
        # "product",
        # "stock",
        # "sale_stock",
        # "mrp",
        # "ad_container_booking",
        # "ad_product_info_bitratex",
        # "ad_account_optimization",
        # "ad_beacukai_report",
        ],
    "author": "Jhony - Bitratex",
    "category": "Purchases",
    "description": """
     This modules is aimed to provide stock report in Bitratex Industries
    """,
    "init_xml": [],
    'update_xml': ["wizard_pending_shipment_register_report.xml",
                    "wizard_pending_shipment_status_register.xml",
                    "wizard_pending_purchase_order_report.xml",
                    "wizard_purchase_receipt_details_view.xml",
                   ],
    'demo_xml': [],
    'installable': True,
    'active': False,
    'application':True,
}